#!/bin/bash
set -eo pipefail # stop if any error

exec () {
  FYTHON_CODE=$1
  ERLANG_PATHS=${@:2}

  ERLANG_PATHS_FORMATED=""
  for ERL_PATH in $ERLANG_PATHS; do
    ERLANG_PATHS_FORMATED=$ERLANG_PATHS_FORMATED"-pa $ERL_PATH "
  done
  erl $ERLANG_PATHS_FORMATED -noshell -eval "'Fython.Core':eval_string(<<"'"'"$FYTHON_CODE"'"'">>)." -run init stop
}

$*