#!/usr/bin/env escript
%% -*- erlang -*-
%%! -smp enable -sname factorial -mnesia debug verbose
-define(main, 'Elixir.Main').

main(["compile"]) ->
    load_deps(),
    G = ?main:compile(param),
    io:format("~w\n", [G]);

main(["shell"]) ->
    load_deps(),
    ?main:shell();

main(_) ->
    usage().


usage() ->
    io:format("usage: fython [compile|shell]\n"),
    halt(1).

load_deps() ->
    code:add_patha("./beams/elixir_beams"),
    code:add_patha("./beams/fython_compiler_beams"),
    code:add_patha("./compiled").
