#!/usr/bin/env escript
%% -*- erlang -*-
%%! -smp enable -sname factorial -mnesia debug verbose
-define(main, 'Elixir.Main').

main([String]) ->
    code:add_patha("./beams/elixir_beams"),
    code:add_patha("./beams/fython_compiler_beams"),
    code:add_patha("./compiled"),
    G = ?main:compile(String),
    io:format("factorial ~w = ~w\n", [String,G]);

main(_) ->
    usage().

usage() ->
    io:format("usage: factorial integer\n"),
    halt(1).
