name: Create Release
on:
  pull_request:
    types:
      - closed
    branches:
      - master
jobs:
  create-release:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v6.1
        with:
          github_token: ${{ secrets.SECRET }}

      - name: Build Changelog
        id: github_release
        uses: mikepenz/release-changelog-builder-action@v3
        env:
          GITHUB_TOKEN: ${{ secrets.SECRET }}
        with:
          configurationJson: |
            {
              "template": "#{{CHANGELOG}}\n\n<details>\n<summary>Uncategorized</summary>\n\n#{{UNCATEGORIZED}}\n</details>",
              "categories": [
                {
                  "title": "## 🚀 Features",
                  "labels": ["feature"]
                },
                {
                  "title": "## 🐛 Fixes",
                  "labels": ["fix"]
                }
              ]
            }
      - name: Create a GitHub release
        uses: ncipollo/release-action@v1
        with:
          tag: ${{ steps.tag_version.outputs.new_tag }}
          name: ${{ steps.tag_version.outputs.new_tag }}
          body: ${{steps.github_release.outputs.changelog}}

      - name: Build
        run: make bootstrap-with-docker && make compress-to-release
      - uses: AButler/upload-release-assets@v2.0
        with:
          files: '_compiled.tar.gz'
          repo-token: ${{ secrets.SECRET }}
          release-tag: ${{ steps.tag_version.outputs.new_tag }}